version: '3.8'

services:
  db:
    image: postgres:17
    container_name: warehouse_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data # Volume persistant pour les données
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db_data: